### ISSUE TITLE
リポジトリ名変えてみたらいかがでしょうか？

### ISSUE THREAD

**Issue by yasyasyu** [shintaro129/EnExMgmt-p1#1]
現在のリポジトリ名よりもわかりやすいAccessManagementSystemにしてみてはいかがでしょうか。

**Comment by shintaro129** [comment]
分かりやすいと思えないので却下で。(ManagementにAccessするシステムではないのでは？)

**Comment by shintaro129** [comment]
> 現在のリポジトリ名よりもわかりやすいAccessManagementSystemにしてみてはいかがでしょうか。
